name: CI

on:
  schedule:
     # actually, ~5 minutes is the highest effective frequency you will get
    - cron:  '* * * * *'

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:

  build:
    
    runs-on: ubuntu-latest

    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3

      - name: Update txt file
        run: |
          git config user.name 'demo-name'
          git config user.email 'demo-email'
          python demo.py
          git commit -am "[BOT] update txt"
          git push
