---
name: Send email

# Job to run main task and send an email only the first time the task fails 
# Based on: https://www.softwaretester.blog/detecting-github-workflow-job-run-status-changes

'on':
  workflow_dispatch:

jobs:
  exampleJob:
    runs-on: ubuntu-latest
    steps:
      - name: Send mail 2
        run: |
          curl -s https://gist.githubusercontent.com/IgnacioHeredia/5f8fd2fc7d56763e4060c7b8fc8e0212/raw/3b5915cf3b8e0fd3c67b7ef7a019175116f0c367/send_email.py | \
          python - \
          --from_user ${{secrets.FROM_MAIL_USERNAME}} \
          --from_pwd ${{secrets.FROM_MAIL_PASSWORD}} \
          --to_user ${{secrets.TO_MAIL_USERNAME}} \
          --subject "Failed Github workflow"          

      - name: Send mail
        uses: dawidd6/action-send-mail@v3
        with:
          server_address: smtp-mail.outlook.com
          server_port: 587
          secure: true
          username: ${{secrets.FROM_MAIL_USERNAME}}
          password: ${{secrets.FROM_MAIL_PASSWORD}}
          subject: Failed Github workflow
          to: ${{secrets.TO_MAIL_USERNAME}}
          from: ${{secrets.FROM_MAIL_USERNAME}}
