---
name: 'Github Workflow History'

'on':
  workflow_dispatch:
    inputs:
      failJob:
        description: Fail the job?
        type: boolean
        required: true
        default: false

jobs:
  exampleJob:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Check last job status
        id: lastJobStatus
        if: always()
        run: |
          LAST_JOB_STATUS=$(gh run list --workflow workflow_history.yaml | grep -oh "completed.*" | head -1 | awk '{print $2}')
          echo "::set-output name=status::$LAST_JOB_STATUS"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} 

      - name: Showcase output variable
        if: always() && steps.lastJobStatus.outputs.status == 'success'
        run: echo "keep running the workflow!!!"

      - name: Pass or fail job
        run: exit 1
        if: github.event.inputs.failJob == 'true'
