---
name: 'Github Workflow History'

# Job to run main task and send an email only the first time the task fails 
# Based on: https://www.softwaretester.blog/detecting-github-workflow-job-run-status-changes

'on':
  workflow_dispatch:
    inputs:
      failJob:
        description: Fail the job?
        type: boolean
        required: true
        default: false

jobs:
  exampleJob:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Pass or fail job
        id: main_task
        run: exit 1
        if: github.event.inputs.failJob == 'true'

      - name: Check last job status
        id: lastJobStatus
        if: always()
        run: |
          LAST_JOB_STATUS=$(gh run list --workflow workflow.yml | grep -oh "completed.*" | head -1 | awk '{print $2}')
          echo "::set-output name=status::$LAST_JOB_STATUS"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} 

      # Only send email the first time the workflow fails
      # (ie. job fails and the previous job run was successful)
      # Otherwise you would receive an email in each of the subsequent failures
      - name: Send email
        if: always() &&  steps.main_task.outcome == 'failure' && steps.lastJobStatus.outputs.status == 'success'
        run: echo "send email!!!"       
